version: '3.7'

services:
  golang_aula:
    image: golang:latest
    container_name: go
    working_dir: /app
    volumes:
      - $HOME/workspace/bob:/app
    command: go run main.go
    ports:
      - "8080:8080"
    networks:
      - custom_network

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    networks:
      - custom_network

  mongo:
    image: mongo:latest
    volumes:
      - ./mongo_data:/data/db
    networks:
      - custom_network

  set_vm_max_map_count:
    image: busybox
    command: sysctl -w vm.max_map_count=262144
    privileged: true
    restart: "no"
    networks:
      - custom_network

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.10.2
    container_name: elasticsearch
    environment:
      - node.name=elasticsearch
      - cluster.name=es-docker-cluster
      - cluster.initial_master_nodes=elasticsearch
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ./es_data:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    networks:
      - custom_network

  graylog:
    image: graylog/graylog:5.2
    volumes:
      - ./graylog_journal:/usr/share/graylog/data/journal
    environment:
      # SET TIMEZONE CONTAINER AND GRAYLOG
      - TZ=America/Sao_Paulo
      - GRAYLOG_ROOT_TIMEZONE=America/Sao_Paulo
      # CHANGE ME (must be at least 16 characters)!
      - GRAYLOG_PASSWORD_SECRET=somepasswordpepper
      - GRAYLOG_ROOT_PASSWORD_SHA2=8c6976e5b5410415bde908bd4dee15dfb167a9c873fc4bb8a81f6f2ab448a918
      - GRAYLOG_HTTP_EXTERNAL_URI=http://127.0.0.1:9000/
      - GRAYLOG_ELASTICSEARCH_INDEX_PREFIX=graylog
      - GRAYLOG_ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    depends_on:
      - elasticsearch
      - mongo
    ports:
      # GELF TCP LOG
      - 12201:12201
      # - 1514:1514
      - 9000:9000
    networks:
      - custom_network

networks:
  custom_network:
    driver: bridge


  # prometheus:
  #   image: prom/prometheus
  #   volumes:
  #     - "./prometheus.yml:/etc/prometheus/prometheus.yml"
  #   ports:
  #     - 9090:9090
